Implement from for u32 and arrays
RoaringBitmap/roaring-rs pull request #248
Opened 2022-10-10 14:54 UTC by michaelmior

This is some convenience methods to allow things like `RoaringBitmap::from(10)` and `RoaringBitmap::from([1,2,3])`.

2022-10-11 19:16 UTC, Kerollmops requested changes
Thank you very much, it looks great!
Would it be possible to do another PR with the same two impl, but for `u64`, for the `RoaringTreemap`, please?

2022-10-11 19:16 UTC, Kerollmops commented on src/bitmap/iter.rs
> +        RoaringBitmap::from_sorted_iter(arr.into_iter()).unwrap()
I would prefer that you don't do more than what this function should do and don't sort here.

```suggestion
        RoaringBitmap::from_iter(arr.into_iter())
```

2022-10-11 23:30 UTC, michaelmior commented
@Kerollmops I made the requested change. Do you want a separate PR for `RoaringTreemap` or should I add that to this one?

2022-10-12 02:41 UTC, Dr-Emann commented
I agree with the array constructor, but is `4u32.into()` really an expected thing for a container type? Vec doesn't implement From from its element type, is that something a bitmap should?

2022-10-12 08:37 UTC, Kerollmops commented
> I agree with the array constructor, but is `4u32.into()` really an expected thing for a container type? Vec doesn't implement From from its element type, is that something a bitmap should?

I agree with you I blindly accepted the change! What I would suggest would be to either not implement anything for one single `u32` as a user can simply call `RoaringBitmap::from([42])` or maybe create a clearly defined method like `RoaringBitmap::from_one(u32)`. What do you think about that @michaelmior @Dr-Emann?

> @Kerollmops I made the requested change. Do you want a separate PR for `RoaringTreemap` or should I add that to this one?

I would like that in this PR, please. But would it be possible to rename it when changes are done? Maybe only implementing the `From<[u32]>`/`From<[u64]>` thing would be enough for now?

2022-10-13 11:59 UTC, michaelmior commented
@Kerollmops I removed the implementation for u32 and added one for u64 arrays in `RoaringTreemap`

2022-10-13 13:18 UTC, Kerollmops approved these changes
bors merge

2022-10-13 13:31 UTC, Kerollmops approved these changes
bors merge

2022-10-13 13:51 UTC, Kerollmops commented
I don't know what's happening with bors. It looks like it is trying to compile the benchmarks, which is probably using to much RAM and killing the process.

2022-10-13 13:51 UTC, Kerollmops approved these changes
bors merge

2022-10-13 16:07 UTC, Kerollmops commented
Unfortunately, I am forced to merge by hand as the CI (called by bors) doesn't let me merge!

2022-10-13 16:12 UTC, merged

2022-10-13 19:24 UTC, michaelmior commented
@Kerollmops Thanks for the merge!