implement range based iteration
RoaringBitmap/roaring-rs pull request #297
Opened 2024-11-11 19:55 UTC by Dr-Emann

Implement `bitmap.iter_range()` and `bitmap.into_iter_range()`, based on `advance_to()` and `advance_back_to()`. Closes #290.

Open questions:
- The equivalent to `.iter_range` for `BTreeSet` is called `.range()` (and so does #290). Is that a better name: `.range`/`.iter_range`? We also need an owning version, `into_range` vs `into_iter_range`?
- `.range` on `BTreeSet` panics on start > end. (or start == end when both are excluded). Should we?

2024-11-12 10:47 UTC, Kerollmops requested changes
Thank you for this PR @Dr-Emann,

I see that this PR is mostly the same as #298. Can you rebase on main once #299 is merged, please?

However, you propose interesting open questions that I will try to answer here.

> The equivalent to `.iter_range` for `BTreeSet` is called `.range()` (and so does https://github.com/RoaringBitmap/roaring-rs/pull/290). Is that a better name: `.range/.iter_range`? We also need an owning version, `into_range` vs `into_iter_range`?

I indeed prefer that we use the `range` naming instead of the `iter_range`. This way, as you propose, we will be closer to the standard naming. I also think that, at some point, we will want to support extracting ranges but we will probably name this method `extract_range`.

> `.range` on `BTreeSet` panics on `start > end`. (or `start == end` when both are excluded). Should we?

Yes, I think a range with a `start > end` is not expected and most likely an error. We should panic. Same for the `start == end` case.

2024-11-12 12:38 UTC, Dr-Emann commented
Hmm, the current utility to to an inclusive range can't currently differentiate `1..1` (an empty range I assume we want to allow) from `1..=0` (an empty range I assume we want to disallow.

2024-11-13 08:55 UTC, Kerollmops commented
> the current utility to to an inclusive range can't currently differentiate `1..1` (an empty range I assume we want to allow) from `1..=0` (an empty range I assume we want to disallow.

Can we do it by hand then? If we cannot then, I think, it's better to just accept them as we don't want to panic for valid empty ranges.

2024-11-15 02:43 UTC, Dr-Emann commented
@Kerollmops Looks like another dependency update broke the MSRV.

2024-11-25 13:12 UTC, Kerollmops commented
Hey @Dr-Emann 👋

> Looks like another dependency update broke the MSRV.

Would you mind rebasing on main when #289 is merged? I bumped the MSRV to 1.71.1 (again).

2024-11-25 22:09 UTC, Kerollmops requested changes
Whoops, still some formating issue 😞

2024-11-27 09:02 UTC, Kerollmops approved these changes
Looks perfect to me, thank you very much for the hard work and patience 🐢

2024-11-27 09:02 UTC, Kerollmops commented on roaring/src/bitmap/util.rs
> +pub fn convert_range_to_inclusive<R>(range: R) -> Result<RangeInclusive<u32>, ConvertRangeError>
Indeed the code is not pretty but it is very useful, thank you 😊

2024-11-27 09:02 UTC, merged