bugfix:deserialize:cotainers max len should be u32
RoaringBitmap/roaring-rs pull request #75
Opened 2020-11-05 07:11 UTC by detailyang

Hello.

RoaringBitmap's cotainers max len should be u32::max_value() rather then u16 in deserialize.

2020-11-05 09:45 UTC, Kerollmops commented
Hey,

Have you checked that in [the RoaringBitmap format specification](https://github.com/RoaringBitmap/RoaringFormatSpec)?
Because IIRC there cannot be more than 2^16 containers where each container contains from 0 to 2^16 numbers.

But maybe you are right :)

2020-11-05 13:30 UTC, lemire commented
The actual cardinality is between 1 and 2^16, and 2^16 will overflow a 16-bit word. The workaround is to represent the cardinality as a number between 0 and 2^16-1 with the convention that empty containers are prohibited: this works during serialization and deserialization because we never store or load an empty container.

2020-11-06 04:00 UTC, detailyang commented
@lemire @Kerollmops 

Sorry. I  just recently read the spec [https://github.com/RoaringBitmap/RoaringFormatSpec](https://github.com/RoaringBitmap/RoaringFormatSpec), The container length max should be 2^16 rather than 2 ^ 32 or 2^16-1.

Checkout the test case named `test_bitmap_high16bits` :)

Many thanks!

2020-11-09 09:18 UTC, detailyang commented
@Kerollmops Can you have look at this? I'm sure the u16::max_value is not right :) See the test case named test_bitmap_high16bits

Many thanks

2020-11-09 09:24 UTC, Kerollmops commented
Yeah, I will take a look at that, thank you for your time :)

bors try

2020-11-09 09:37 UTC, Kerollmops requested changes
Indeed you have found a bug in the deserialization process, thank you very much! Could you just fix the fmt issue that I suggested to you, please?

To resume your test, you insert big numbers until 2^32, the maximum possible value, these big numbers will force the RoaringBitmap to create a container for each one of those (?), resulting in 2^16 containers. Finally you check that you are able to deserialize them.

And to fix this bug, you have modified the condition that was checking for a correct amount of containers that was under 2^16 instead of 2^16+1.

2020-11-09 09:37 UTC, Kerollmops commented on tests/serialization.rs
> +    for i in 0..1<<16 {
```suggestion
    for i in 0..1 << 16 {
```

2020-11-09 09:52 UTC, detailyang commented on tests/serialization.rs
> +    for i in 0..1<<16 {
Done:)

2020-11-09 14:04 UTC, Kerollmops approved these changes
Thank you!

bors r+

2020-11-09 22:08 UTC, Kerollmops approved these changes
bors r+

2020-11-09 22:11 UTC, merged