Better push method
RoaringBitmap/roaring-rs pull request #99
Opened 2021-04-28 10:09 UTC by MarinPostma

2021-04-28 11:06 UTC, Kerollmops commented
Thank you very much.

bors try

2021-04-28 11:39 UTC, MarinPostma commented
sorry, forgot to run fmt. fixed now :)

2021-04-28 11:59 UTC, Kerollmops commented
Thank you 🧷,

However, I will not be able to merge it before #97, as this is a breaking PR, and #97 is not.
I would like to release a 0.6.7 for #97 and then a 0.7.0 for this one.

bors try

2021-04-29 09:01 UTC, Kerollmops requested changes
Could you please fixup (with only one commit message) the first three commits, please?
Keep the clippy fixes in one separate commit.

2021-04-29 09:20 UTC, Kerollmops commented
Added the clippy fix of @MarinPostma.

bros try

2021-04-29 18:50 UTC, Kerollmops approved these changes
Thank you, LGTM!

bors merge

2021-04-29 18:54 UTC, merged